/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package sg.com.bigspoon.www;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int bg_logo=0x7f020000;
        public static final int bigspoon_splash_640_960=0x7f020001;
        public static final int bigspoonmobileappiconwithname=0x7f020002;
        public static final int custom_tab_indicator=0x7f020003;
        public static final int custom_tab_indicator_divider=0x7f020004;
        public static final int custom_tab_indicator_focused=0x7f020005;
        public static final int custom_tab_indicator_selected=0x7f020006;
        public static final int custom_tab_indicator_selected_focused=0x7f020007;
        public static final int custom_tab_indicator_selected_pressed=0x7f020008;
        public static final int custom_tab_indicator_unselected=0x7f020009;
        public static final int custom_tab_indicator_unselected_focused=0x7f02000a;
        public static final int custom_tab_indicator_unselected_pressed=0x7f02000b;
        public static final int down=0x7f02000c;
        public static final int email=0x7f02000d;
        public static final int ic_launcher=0x7f02000e;
        public static final int icon=0x7f02000f;
        public static final int intro_1=0x7f020010;
        public static final int intro_2=0x7f020011;
        public static final int intro_3=0x7f020012;
        public static final int intro_4=0x7f020013;
        public static final int intro_5=0x7f020014;
        public static final int intro_bottom=0x7f020015;
        public static final int login_box_bg=0x7f020016;
        public static final int login_bt=0x7f020017;
        public static final int login_btn_new=0x7f020018;
        public static final int middle=0x7f020019;
        public static final int middle_withoutborder=0x7f02001a;
        public static final int new_entry_background=0x7f02001b;
        public static final int new_fb_btn=0x7f02001c;
        public static final int new_signup_btn=0x7f02001d;
        public static final int or_separator=0x7f02001e;
        public static final int password=0x7f02001f;
        public static final int perm_group_calendar=0x7f020020;
        public static final int perm_group_calendar_normal=0x7f020021;
        public static final int perm_group_calendar_selected=0x7f020022;
        public static final int perm_group_camera=0x7f020023;
        public static final int perm_group_camera_normal=0x7f020024;
        public static final int perm_group_camera_selected=0x7f020025;
        public static final int perm_group_device_alarms=0x7f020026;
        public static final int perm_group_device_alarms_normal=0x7f020027;
        public static final int perm_group_device_alarms_selected=0x7f020028;
        public static final int perm_group_location=0x7f020029;
        public static final int perm_group_location_normal=0x7f02002a;
        public static final int perm_group_location_selected=0x7f02002b;
        public static final int signup_btn_new=0x7f02002c;
        public static final int top=0x7f02002d;
    }
    public static final class id {
        public static final int action_settings=0x7f08000c;
        public static final int add_page=0x7f08000e;
        public static final int bottom=0x7f080009;
        public static final int imageButton1=0x7f080005;
        public static final int imageButton2=0x7f080008;
        public static final int imageButton3=0x7f080007;
        public static final int imageView1=0x7f080006;
        public static final int imageView2=0x7f080002;
        public static final int indicator=0x7f080001;
        public static final int middle=0x7f08000a;
        public static final int pager=0x7f080000;
        public static final int random=0x7f08000d;
        public static final int remove_page=0x7f08000f;
        public static final int search=0x7f080003;
        public static final int search2=0x7f080004;
        public static final int top=0x7f08000b;
    }
    public static final class layout {
        public static final int activity_circle=0x7f030000;
        public static final int activity_launch=0x7f030001;
        public static final int activity_login=0x7f030002;
        public static final int activity_main=0x7f030003;
        public static final int activity_sign_up=0x7f030004;
        public static final int activity_tutorial_screen1=0x7f030005;
        public static final int activity_tutorial_screen2=0x7f030006;
        public static final int activity_tutorial_screen3=0x7f030007;
        public static final int activity_tutorial_screen4=0x7f030008;
        public static final int activity_tutorial_screen5=0x7f030009;
        public static final int activity_tutorial_screen6=0x7f03000a;
        public static final int activity_tutorial_screenlast=0x7f03000b;
    }
    public static final class menu {
        public static final int circle=0x7f070000;
        public static final int entry=0x7f070001;
        public static final int launch=0x7f070002;
        public static final int login=0x7f070003;
        public static final int main=0x7f070004;
        public static final int menu=0x7f070005;
        public static final int sign_up=0x7f070006;
        public static final int tutorial_screen1=0x7f070007;
        public static final int tutorial_screen6=0x7f070008;
    }
    public static final class string {
        public static final int action_settings=0x7f050007;
        public static final int app_id=0x7f050010;
        public static final int app_name=0x7f050000;
        public static final int email=0x7f05000b;
        public static final int emailAddress=0x7f05000d;
        public static final int fullName=0x7f05000e;
        public static final int hello_world=0x7f050008;
        public static final int password=0x7f05000c;
        public static final int title_activity_entry=0x7f050004;
        public static final int title_activity_launch=0x7f050003;
        public static final int title_activity_launcher=0x7f050002;
        public static final int title_activity_login=0x7f050009;
        public static final int title_activity_sign_up=0x7f05000a;
        public static final int title_activity_tutorial=0x7f050005;
        public static final int title_activity_tutorial_screen1=0x7f050001;
        public static final int title_activity_tutorial_screen6=0x7f050006;
        public static final int title_activity_xyz=0x7f05000f;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060001;
    }
}
